name: Pull Request

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Node.js v16.15.1
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
    - name: Instalar dependências
      run: npm install
    - name: Analisando código com ESLint
      run: npx eslint "src/**/*.{js,jsx}"
